// ============================================================
// MavenTech Sales Pipeline — DAX Measures
// All measures use CALCULATE + filter context patterns.
// NO calculated columns — all logic lives here.
// ============================================================
// Load order: base counts first, then rates, then time intel.
// ============================================================


// ════════════════════════════════════════════════════════════
// TABLE: _Measures  (empty table used as measure container)
// ════════════════════════════════════════════════════════════


// ────────────────────────────────────────────────────────────
// SECTION 1 — BASE COUNTS
// ────────────────────────────────────────────────────────────

[Total Opportunities] =
COUNTROWS( fact_opportunities )

[Opportunities Won] =
CALCULATE(
    COUNTROWS( fact_opportunities ),
    fact_opportunities[deal_stage] = "Won"
)

[Opportunities Lost] =
CALCULATE(
    COUNTROWS( fact_opportunities ),
    fact_opportunities[deal_stage] = "Lost"
)

[Closed Opportunities] =
CALCULATE(
    COUNTROWS( fact_opportunities ),
    fact_opportunities[is_closed] = TRUE()
)

[Open Opportunities] =
CALCULATE(
    COUNTROWS( fact_opportunities ),
    fact_opportunities[is_closed] = FALSE()
)

[Reached Engaging] =
CALCULATE(
    COUNTROWS( fact_opportunities ),
    fact_opportunities[reached_engaging] = TRUE()
)

[Died at Prospecting] =
CALCULATE(
    COUNTROWS( fact_opportunities ),
    fact_opportunities[reached_engaging] = FALSE()
)


// ────────────────────────────────────────────────────────────
// SECTION 2 — REVENUE
// ────────────────────────────────────────────────────────────

[Closed-Won Revenue] =
CALCULATE(
    SUM( fact_opportunities[close_value] ),
    fact_opportunities[deal_stage] = "Won"
)

[Avg Deal Size (Won)] =
CALCULATE(
    AVERAGE( fact_opportunities[close_value] ),
    fact_opportunities[deal_stage] = "Won"
)

[Median Deal Size (Won)] =
CALCULATE(
    MEDIAN( fact_opportunities[close_value] ),
    fact_opportunities[deal_stage] = "Won"
)

// Pipeline value = sum of list price for open Engaging deals
// Uses dim_product[sales_price] as proxy for unrealized value
[Open Pipeline Value] =
CALCULATE(
    SUMX(
        fact_opportunities,
        RELATED( dim_product[sales_price] )
    ),
    fact_opportunities[deal_stage] = "Engaging"
)


// ────────────────────────────────────────────────────────────
// SECTION 3 — CONVERSION RATES
// ────────────────────────────────────────────────────────────

// Prospecting → Engaging conversion
// = # that reached Engaging ÷ all opportunities
[Prospecting to Engaging Rate] =
DIVIDE( [Reached Engaging], [Total Opportunities] )

// Win rate = Won ÷ (Won + Lost)  — excludes open deals
// This is the correct denominator for a closed-deal win rate.
// Do NOT use [Total Opportunities] as denominator: it would
// penalise reps carrying large open pipelines unfairly.
[Win Rate] =
DIVIDE( [Opportunities Won], [Closed Opportunities] )

// Lost rate (complement of win rate)
[Lost Rate] =
DIVIDE( [Opportunities Lost], [Closed Opportunities] )


// ────────────────────────────────────────────────────────────
// SECTION 4 — CYCLE LENGTH
// ────────────────────────────────────────────────────────────

[Avg Sales Cycle (Days)] =
CALCULATE(
    AVERAGE( fact_opportunities[days_to_close] ),
    fact_opportunities[deal_stage] = "Won",
    NOT ISBLANK( fact_opportunities[days_to_close] )
)

[Median Sales Cycle (Days)] =
CALCULATE(
    MEDIAN( fact_opportunities[days_to_close] ),
    fact_opportunities[deal_stage] = "Won",
    NOT ISBLANK( fact_opportunities[days_to_close] )
)

// Flag deals ageing in Engaging > 60 days without closing
[Stale Open Deals (>60d)] =
CALCULATE(
    COUNTROWS( fact_opportunities ),
    fact_opportunities[deal_stage] = "Engaging",
    DATEDIFF( fact_opportunities[engage_date], TODAY(), DAY ) > 60
)


// ────────────────────────────────────────────────────────────
// SECTION 5 — TIME INTELLIGENCE
// Requires dim_date marked as Date Table in model.
// Relationships: fact_opportunities[engage_date] → dim_date[date]
//                fact_opportunities[close_date]  → dim_date_close[date]
// ────────────────────────────────────────────────────────────

[Revenue YTD] =
CALCULATE(
    [Closed-Won Revenue],
    DATESYTD( dim_date[date] )
)

[Revenue Prior Year YTD] =
CALCULATE(
    [Closed-Won Revenue],
    DATESYTD( SAMEPERIODLASTYEAR( dim_date[date] ) )
)

[Revenue YoY % Change] =
DIVIDE(
    [Revenue YTD] - [Revenue Prior Year YTD],
    [Revenue Prior Year YTD]
)

[Revenue Prior Period] =
CALCULATE(
    [Closed-Won Revenue],
    PREVIOUSQUARTER( dim_date[date] )
)

[Revenue QoQ % Change] =
DIVIDE(
    [Closed-Won Revenue] - [Revenue Prior Period],
    [Revenue Prior Period]
)

// Rolling 3-month revenue (smooths volatility)
[Revenue Rolling 3M] =
CALCULATE(
    [Closed-Won Revenue],
    DATESINPERIOD( dim_date[date], LASTDATE( dim_date[date] ), -3, MONTH )
)


// ────────────────────────────────────────────────────────────
// SECTION 6 — REP & MANAGER PERFORMANCE
// ────────────────────────────────────────────────────────────

// Win rate rank within region (lower number = better)
[Win Rate Rank (Region)] =
RANKX(
    ALLSELECTED( dim_agent[sales_agent] ),
    [Win Rate],
    ,
    DESC,
    DENSE
)

// Revenue rank across all agents
[Revenue Rank (All)] =
RANKX(
    ALL( dim_agent[sales_agent] ),
    [Closed-Won Revenue],
    ,
    DESC,
    DENSE
)

// Avg win rate for manager's team (used for variance callout)
[Manager Team Win Rate] =
CALCULATE(
    [Win Rate],
    ALLEXCEPT( dim_agent, dim_agent[manager] )
)

// Individual vs. team delta
[Win Rate vs. Team] =
[Win Rate] - [Manager Team Win Rate]


// ────────────────────────────────────────────────────────────
// SECTION 7 — PRODUCT PERFORMANCE
// ────────────────────────────────────────────────────────────

[Win Rate vs. Avg] =
[Win Rate] - CALCULATE( [Win Rate], ALL( dim_product ) )

// ACV premium: avg closed-won value vs. list price
[ACV vs. List Price] =
[Avg Deal Size (Won)] - AVERAGE( dim_product[sales_price] )

// Discount depth proxy (negative = selling below list)
[ACV / List Price Ratio] =
DIVIDE(
    [Avg Deal Size (Won)],
    CALCULATE( AVERAGE( dim_product[sales_price] ), ALLEXCEPT( dim_product, dim_product[product] ) )
)


// ────────────────────────────────────────────────────────────
// SECTION 8 — COHORT ANALYSIS
// Used on the deal cohort matrix (Page 2)
// Row context = month_opened, Column context = quarter_closed
// ────────────────────────────────────────────────────────────

// Win rate for the intersecting cohort cell
[Cohort Win Rate] =
DIVIDE(
    CALCULATE(
        [Opportunities Won],
        fact_opportunities[is_closed] = TRUE()
    ),
    CALCULATE(
        [Closed Opportunities]
    )
)

// Avg cycle for cohort cell
[Cohort Avg Cycle (Days)] =
CALCULATE(
    [Avg Sales Cycle (Days)],
    fact_opportunities[is_closed] = TRUE()
)

// Revenue realized per cohort
[Cohort Revenue] =
CALCULATE(
    [Closed-Won Revenue],
    fact_opportunities[is_closed] = TRUE()
)


// ────────────────────────────────────────────────────────────
// SECTION 9 — DYNAMIC TITLES (for report headers)
// ────────────────────────────────────────────────────────────

[Selected Region Label] =
IF(
    ISFILTERED( dim_agent[regional_office] ),
    "Region: " & SELECTEDVALUE( dim_agent[regional_office], "Multiple" ),
    "All Regions"
)

[Win Rate Card Label] =
FORMAT( [Win Rate], "0.0%" ) & " Win Rate"

[Revenue Card Label] =
"$" & FORMAT( [Closed-Won Revenue] / 1000000, "0.00" ) & "M Closed-Won"
